# Permalinks
permalink:           pretty

plugins:
  - jekyll-paginate

# Setup
title:               Leslie Cannold
url:                 'https://www.cannold.com'

# About/contact
author:
  name:              'Strategic Data'
  email:             'support@strategicdata.com.au'

exclude:
  - node_modules
  - vendor
  - src
  - gulpfile.js
  - bower_components
  - bower.json
  - README.md
  - static
  - package.json
  - '*.sh'
  - nginx.d
  - blueprint
  - 2000-cannold-com.tgz
  - builder.dockerfile
  - Dockerfile
  - docker-compose.yml
  - cannold.com.tgz
  - Gemfile*
  - canvas-templates

paginate: 10
paginate_path: "/blog/page:num/"

future: true

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "pages"
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "posts"
      permalink: "/blog/:year-:month-:day-:title/"
